version: '3'
services:
  db:
    container_name: course
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
      - MSSQL_PID=Developer